when:
- event: push
  branch: ${CI_REPO_DEFAULT_BRANCH}

steps:
- name: release-helper
  image: registry.yewolf.fr/wrapper/wrap/ghcr.io/yyewolf/woodpecker-plugins/release-please/latest/with/ghcr.io/yyewolf/woodpecker-plugins/github-token-wrapper/latest:latest
  settings:
    repo_url: ${CI_REPO_URL}
    release_type: go
    target_branch: main
    mtls_service_url: https://github-token-svc:8443/token
    mtls_ca_cert:
      from_secret: GITHUB_MTLS_CA_CERT
    mtls_client_cert:
      from_secret: GITHUB_MTLS_CLIENT_CERT
    mtls_client_key:
      from_secret: GITHUB_MTLS_CLIENT_KEY
    output_to: PLUGIN_TOKEN

services:
- name: github-token-svc
  image: ghcr.io/yyewolf/woodpecker-plugins/github-app-token-svc
  ports:
  - 8443
  settings:
    github_app_id:
      from_secret: GH_APP_ID
    github_installation_id:
      from_secret: GH_INSTALL_ID
    github_private_key_pem:
      from_secret: GH_APP_PEM
    mtls_ca_cert:
      from_secret: GITHUB_MTLS_CA_CERT
    mtls_server_cert:
      from_secret: GITHUB_MTLS_SERVER_CERT
    mtls_server_key:
      from_secret: GITHUB_MTLS_SERVER_KEY
